Remove unused soft_budget & send_invite_email params
that `test_cli_sync.py` detected!

```
E       AssertionError: Extra fields in CLI update command: {'soft_budget', 'send_invite_email'}
E       assert not {'send_invite_email', 'soft_budget'}

tests/litellm/proxy/client/cli/test_cli_sync.py:44: AssertionError
```