Pin to openai==1.68.2 to fix mypy errors
Pin to openai==1.68.2 to prevent these errors:

```shell
(.venv)
abramowi at Marcs-MBP-3 in ~/Code/OpenSource/litellm/litellm (main)
$ poetry run mypy . --ignore-missing-imports
...
types/utils.py:1512: error: Incompatible types in assignment (expression has type "litellm.types.utils.Usage", base class "ImagesResponse" defined the type as "openai.types.images_response.Usage | None")  [assignment]
litellm_core_utils/fallback_utils.py:41: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
integrations/dynamodb.py:19: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
caching/redis_cache.py:919: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
llms/vertex_ai/image_generation/cost_calculator.py:22: error: Argument 1 to "len" has incompatible type "list[Image] | None"; expected "Sized"  [arg-type]
llms/bedrock/image/cost_calculator.py:40: error: Argument 1 to "len" has incompatible type "list[Image] | None"; expected "Sized"  [arg-type]
integrations/s3.py:123: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
...
Found 3 errors in 3 files (checked 760 source files)
```