fix: enhance AzureOpenAIResponsesAPIConfig to support different Azure auth method like we have for completions api. (#10871)
* fix: enhance AzureOpenAIResponsesAPIConfig to support different Azure Auth method like we have for completions api.

* extract duplicate code to common functoin as util for future reference

* remove unused import

* Add type annotation in order to fix this issue.
llms/azure/common_utils.py:416: error: Incompatible types in assignment (expression has type "AsyncClient | None", target has type "str | Callable[[], str] | None")  [assignment]
llms/azure/common_utils.py:418: error: Incompatible types in assignment (expression has type "Client | None", target has type "str | Callable[[], str] | None")  [assignment]

* convert response to pydantic  object and also provide unittest for it

* remove unused type